from pathlib import Path
from playwright.sync_api import sync_playwright
root=Path('/mnt/data/ui_sweep_work')
css_site=(root/'src/shared/styles/site.css').read_text(); css_home=(root/'src/site/styles/home.css').read_text(); css_tools=(root/'src/site/styles/tools.css').read_text(); css_chain=(root/'src/site/styles/chain.css').read_text(); css_game=(root/'src/shared/styles/game-settings.css').read_text()
base='''<style>:root{--site-bg:#fff;--site-fg:#121213;--site-muted:#787c7e;--site-line:#d3d6da;--site-soft:#eee;--site-accent:#787c7e;--site-error:#d33;--site-content-width:1080px}'''+css_site+css_home+css_tools+css_chain+css_game+'</style>'
site='''<div class="site-route site-standard"><header class="top"><a class="brand">Sanyam Brar</a><nav class="top-nav"><a>Work</a><a>Lab</a><button class="top-icon">◐</button><button class="search-trigger"><kbd>Ctrl K</kbd></button></nav></header><main><section class="intro"><div class="intro-meta"><span>Zig</span><span>C++</span><span>Go</span><span>Java</span></div><div class="intro-links"><a>GitHub ↗</a><a>SmallThingz ↗</a></div></section><section><div class="grid"><a class="card"><div class="card-top"><span class="game-title game-wordle"><i>W</i><i>O</i><i>R</i><i>D</i><i>L</i><i>E</i></span><span class="arrow">›</span></div><div class="card-copy">A Wordle clone.</div></a><a class="card"><div class="card-top"><span class="game-title game-keybr"><i>Keybr</i></span><span class="arrow">›</span></div><div class="card-copy">A local-first fork of keybr.com.</div></a><a class="card"><div class="card-top"><span class="game-title game-chain"><span>CHAIN</span><svg viewBox="0 0 58 22"></svg><span>REACTION</span></span><span class="arrow">›</span></div><div class="card-copy">Canvas-rendered chain reaction with local AI.</div></a></div></section><section><div class="compact-list"><a class="compact-row"><span><span class="compact-name">Encode / Decode with a pathologically long title</span><span class="compact-note">Base64, URL, Base32, Base58, hex, binary and text encodings with a long note.</span></span><span class="row-kind">Tool</span><span class="arrow">›</span></a></div></section><article class="project-detail"><p class="eyebrow">Project</p><h1>ridiculously-long-project-identifier-that-should-wrap</h1><p class="dek">A deliberately long description containing https://example.com/a/really/really/really/long/unbroken/path/that/should/not-overflow</p><div class="fact-strip"><span>very-long-unbroken-technical-fact-identifier</span></div></article></main></div>'''
tools='''<div class="site-route tools-page" style="height:100dvh"><header class="top tools-top"><a class="brand">Sanyam Brar</a><nav class="tool-tabs"><a aria-current="page" data-narrow="Text">Text</a><a>Encode</a><a>Diff</a><a>Numbers</a><a>Markdown</a></nav><div class="tool-context"><span><strong>12345</strong><span class="tool-stat-label"> words</span><span class="tool-stat-short">w</span></span><span><strong>98765</strong><span class="tool-stat-label"> chars</span><span class="tool-stat-short">c</span></span><span><strong>123</strong> non-ASCII</span></div><nav class="top-nav tools-site-nav"><a>Work</a><a>Lab</a><button class="top-icon">◐</button><button class="search-trigger"><kbd>Ctrl K</kbd></button></nav></header><main class="tools-app"><div class="tools-view"><section class="number-tool"><div class="number-hero"><label><span>Value</span><input value="123456789012345678901234567890"></label><label><span>Base</span><input id="source-base" value="10"></label><div class="radix-choices"><button>BIN</button><button>OCT</button><button>DEC</button><button>HEX</button></div></div><div class="number-representations"><header><h1>Representations</h1><label>Custom radix<input value="62"></label></header><div class="number-grid"><label class="number-card"><header><span>Binary representation with long label</span><span>base 2</span></header><input value="111111111111111111111111111111111111111111"><button>Copy</button></label></div></div></section></div></main></div>'''
chain='''<div class="site-page-chain"><div class="chain-shell"><section class="chain-view"><header class="top chain-topbar"><button class="chain-title">CHAIN REACTION</button><div class="chain-turn"><span class="chain-turn-item"><span>YOU</span><span class="chain-turn-swatch"></span></span><span class="chain-turn-item"><span>TURN</span><span class="chain-turn-swatch"></span></span></div><div class="chain-top-actions"><button class="game-settings-trigger">◐</button><button class="game-settings-trigger">⚙</button></div></header><main class="chain-stage"><canvas id="chain-canvas" width="300" height="500"></canvas></main></section></div></div>'''
JS='''() => {const vw=document.documentElement.clientWidth;const vis=[...document.querySelectorAll('body *')].filter(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0});const outside=vis.filter(e=>{const r=e.getBoundingClientRect();return r.left<-1||r.right>vw+1}).map(e=>({tag:e.tagName,cls:(e.className||'').toString(),l:Math.round(e.getBoundingClientRect().left),r:Math.round(e.getBoundingClientRect().right),txt:(e.innerText||'').trim().slice(0,60)}));const clips=vis.filter(e=>{if(e.children.length)return false;const t=(e.innerText||'').trim();if(!t)return false;const s=getComputedStyle(e);return ((['hidden','clip'].includes(s.overflowX)||['hidden','clip'].includes(s.overflow))&&e.scrollWidth>e.clientWidth+1)||((['hidden','clip'].includes(s.overflowY)||['hidden','clip'].includes(s.overflow))&&e.scrollHeight>e.clientHeight+1)}).map(e=>({tag:e.tagName,cls:(e.className||'').toString(),sw:e.scrollWidth,cw:e.clientWidth,txt:(e.innerText||'').trim().slice(0,60)}));return {sw:document.documentElement.scrollWidth,outside,clips}}'''
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox'])
 for name,markup in [('site',site),('tools',tools),('chain',chain)]:
  for w,h in [(320,568),(360,640),(375,812),(768,800),(1024,768),(1440,900)]:
   pg=b.new_page(viewport={'width':w,'height':h});pg.set_content(base+markup)
   m=pg.evaluate(JS)
   if m['sw']>w+1 or m['outside'] or m['clips']:
    print(name,w,h,m)
    pg.screenshot(path=f'/mnt/data/ui_sweep_work/layout_{name}_{w}.png',full_page=True)
   pg.close()
 b.close()
