import { createSignal, onCleanup } from 'solid-js';
import type { Entry } from '../data';
function githubReadme(href:string){const u=new URL(href);if(u.hostname==='github.com'&&!u.hash)u.hash='readme';return u.href}
export function ExternalBrowser(props:{entry:Entry}){
  const href=githubReadme(props.entry.href); const [full,setFull]=createSignal(false); let controls!:HTMLDivElement; let drag:null|{id:number,x:number,y:number,left:number,top:number,w:number,h:number,moved:boolean}=null;
  const reset=()=>{controls.style.left='';controls.style.top='';controls.style.right=''};
  const toggle=()=>{setFull(v=>!v);reset()};
  const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&full())toggle()}; addEventListener('keydown',key); onCleanup(()=>removeEventListener('keydown',key));
  const down=(e:PointerEvent)=>{if(!full()||(e.target as Element).closest('button'))return;const r=controls.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top,w:r.width,h:r.height,moved:false};controls.setPointerCapture(e.pointerId)};
  const move=(e:PointerEvent)=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.moved&&Math.hypot(dx,dy)<6)return;drag.moved=true;const m=8,maxL=Math.max(m,innerWidth-drag.w-m),maxT=Math.max(m,innerHeight-drag.h-m);controls.style.right='auto';controls.style.left=`${Math.min(Math.max(m,drag.left+dx),maxL)}px`;controls.style.top=`${Math.min(Math.max(m,drag.top+dy),maxT)}px`};
  const up=(e:PointerEvent)=>{if(!drag||drag.id!==e.pointerId)return;if(controls.hasPointerCapture(e.pointerId))controls.releasePointerCapture(e.pointerId);drag=null};
  return <section class="detail-browser-section" aria-label={`${props.entry.title} preview`}><div class="detail-browser" classList={{fullscreen:full()}}><div ref={controls} class="detail-browser-controls" classList={{draggable:full()}} aria-label="Embedded page controls" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><button class="detail-browser-button" type="button" onClick={()=>window.open(href,'_blank','noopener,noreferrer')} aria-label="Open in new tab" title="Open in new tab"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 3h7v7"/><path d="M10 14L21 3"/><path d="M21 14v7H3V3h7"/></svg></button><span class="detail-browser-divider" aria-hidden="true"/><button class="detail-browser-button" type="button" onClick={toggle} aria-label={full()?'Exit fullscreen':'Enter fullscreen'} title={full()?'Exit fullscreen':'Fullscreen'}><svg viewBox="0 0 24 24" aria-hidden="true">{full()?<><path d="M8 8H3V3"/><path d="M16 8h5V3"/><path d="M8 16H3v5"/><path d="M16 16h5v5"/></>:<><path d="M8 3H3v5"/><path d="M16 3h5v5"/><path d="M8 21H3v-5"/><path d="M16 21h5v-5"/></>}</svg></button></div><iframe src={href} title={props.entry.title} loading="lazy" referrerpolicy="strict-origin-when-cross-origin"/></div></section>}
