import AlarmClockCheck from "lucide-solid/icons/alarm-clock-check";
import CircleAlert from "lucide-solid/icons/circle-alert";
import Maximize2 from "lucide-solid/icons/maximize-2";
import ChartNoAxesColumn from "lucide-solid/icons/chart-no-axes-column";
import CircleCheck from "lucide-solid/icons/circle-check";
import Circle from "lucide-solid/icons/circle";
import Square from "lucide-solid/icons/square";
import SquareCheck from "lucide-solid/icons/square-check";
import X from "lucide-solid/icons/x";
import Settings from "lucide-solid/icons/settings";
import Move from "lucide-solid/icons/move";
import Trash2 from "lucide-solid/icons/trash-2";
import Download from "lucide-solid/icons/download";
import Smile from "lucide-solid/icons/smile";
import Frown from "lucide-solid/icons/frown";
import CircleHelp from "lucide-solid/icons/circle-help";
import House from "lucide-solid/icons/house";
import Info from "lucide-solid/icons/info";
import CirclePlay from "lucide-solid/icons/circle-play";
import CircleDot from "lucide-solid/icons/circle-dot";
import Redo2 from "lucide-solid/icons/redo-2";
import SkipForward from "lucide-solid/icons/skip-forward";
import SkipBack from "lucide-solid/icons/skip-back";
import CircleStop from "lucide-solid/icons/circle-stop";
import SunMoon from "lucide-solid/icons/sun-moon";
import Trophy from "lucide-solid/icons/trophy";
import Undo2 from "lucide-solid/icons/undo-2";
import Upload from "lucide-solid/icons/upload";

export const mdiAlarmCheck = AlarmClockCheck;
export const mdiAlertCircleOutline = CircleAlert;
export const mdiAspectRatio = Maximize2;
export const mdiChartBar = ChartNoAxesColumn;
export const mdiCheckCircle = CircleCheck;
export const mdiCheckCircleOutline = CircleCheck;
export const mdiCheckboxBlankOutline = Square;
export const mdiCheckboxMarkedOutline = SquareCheck;
export const mdiClose = X;
export const mdiCog = Settings;
export const mdiCursorMove = Move;
export const mdiDeleteForever = Trash2;
export const mdiDownload = Download;
export const mdiEmoticonHappy = Smile;
export const mdiEmoticonSad = Frown;
export const mdiHelpCircleOutline = CircleHelp;
export const mdiHome = House;
export const mdiInformationOutline = Info;
export const mdiPlayCircleOutline = CirclePlay;
export const mdiRadioboxBlank = Circle;
export const mdiRadioboxMarked = CircleDot;
export const mdiRedo = Redo2;
export const mdiSkipNext = SkipForward;
export const mdiSkipPrevious = SkipBack;
export const mdiStopCircleOutline = CircleStop;
export const mdiThemeLightDark = SunMoon;
export const mdiTrophy = Trophy;
export const mdiUndo = Undo2;
export const mdiUpload = Upload;
